### PR TITLE
General Changes

### PR DESCRIPTION
**Pull request by hskrtich**
*Return BadGateway http error when no endpoint found
*Add endpoints active so when they go deactive it logs
*Dont disable endpoints outputting error codes since
  you cant fix what you cant see

### CODE REVIEW

**Review by kcmerrill — CHANGES_REQUESTED** [review]
Hmmm ...

I understand the reasoning for making things active so you can see the error codes, but one of the things I was going to implement was A/B releases. By making everything active, the health checks are basically .... useless. 

Maybe we can implement a ?debug or append debug to the subdomain so you can see the error codes. 

Normally if I need to debug something I just go straight to the ports ....

Thoughts?

**Comment by hskrtich** [comment]
The health check would still weed out servers not there, or no response. But an alternative would be to add another command line var of --debug or something.

**Comment by kcmerrill** [comment]
Ahhh, yeah, I actually like that idea better ... an extra command line argument. 

Maybe "--dev" and if set, will set "--insecure" and let everything be active?

**Comment by hskrtich** [comment]
Yes I like that too. I will work on adding that.

**Comment by hskrtich** [comment]
Ok how is that?

**Review by kcmerrill — APPROVED** [review]
Awesome! Thanks!

**Comment by kcmerrill** [comment]
I will update the docker container in the morning. Thanks for the patchset!

**Pull request merged**
